stages:
  - test

test_job:
  stage: test
  image: python:3.9 
  before_script:
    - pip install -r requirements.txt 
    - pip install pytest 
  script:
    - pytest test/
  timeout: 10 minutes  # Batas waktu 10 menit
  artifacts:
    when: always

variables:
  DB_PATH: "database/nomnom.db"
  CONTROLLER_PATH: "controller/controller.py"

before_script:
  - python $CONTROLLER_PATH $DB_PATH  # Inisialisasi koneksi database sebelum menjalankan skrip pytest